# Generated by Django 4.0.4 on 2022-04-30 20:09

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1, verbose_name='Status')),
                ('published_from', models.DateField(verbose_name='Published from')),
                ('published_to', models.DateField(verbose_name='Published to')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('message', models.TextField(max_length=1280, verbose_name='Message')),
                ('dismissible', models.BooleanField(default=True, verbose_name='Dismissible')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
