# Generated by Django 4.0.4 on 2022-05-10 07:30

import banners.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='show_from',
            field=banners.fields.DayMonthField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='show_to',
            field=banners.fields.DayMonthField(),
        ),
    ]
