# Generated by Django 4.0.4 on 2022-05-19 07:49

from django.db import migrations
import fh_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_show_from_alter_banner_show_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='show_from',
            field=fh_utils.fields.DayMonthField(verbose_name='Show From'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='show_to',
            field=fh_utils.fields.DayMonthField(verbose_name='Show To'),
        ),
    ]
