# Generated by Django 4.0.4 on 2022-05-20 18:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_show_from_alter_banner_show_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'default_manager_name': 'admin_objects'},
        ),
        migrations.AlterModelManagers(
            name='banner',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
