version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "16:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 50
    target-branch: main
    versioning-strategy: increase
