# Generated by Django 4.2.1 on 2023-05-25 07:48

from django.db import migrations, models
import django.db.models.deletion
import pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artical",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("banner_title", models.CharField(max_length=60)),
                ("banner_sub_title", models.CharField(max_length=120)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("Paragraph", wagtail.blocks.RichTextBlock()),
                            (
                                "Services",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                        ("body", wagtail.blocks.RichTextBlock(required=False)),
                                        (
                                            "services",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.PageChooserBlock(page_type=["pages.ServicePage"])
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "Item",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                        ("sub_title", wagtail.blocks.CharBlock(max_length=255, required=False)),
                                        ("image", wagtail.images.blocks.ImageChooserBlock()),
                                        ("body", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            ),
                            ("ImageRow", pages.blocks.ImageRow()),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticalList",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("banner_title", models.CharField(max_length=60)),
                ("banner_sub_title", models.CharField(max_length=120)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
