# Generated by Django 4.2.1 on 2023-05-25 07:58

from django.db import migrations
import pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articallist",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("Paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "Services",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("body", wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    "services",
                                    wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=["pages.ServicePage"])),
                                ),
                            ]
                        ),
                    ),
                    (
                        "Item",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("sub_title", wagtail.blocks.CharBlock(max_length=255, required=False)),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("body", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    ("ImageRow", pages.blocks.ImageRow()),
                ],
                default=None,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
