# Generated by Django 4.2.1 on 2023-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_articallist_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artical",
            name="banner_sub_title",
        ),
        migrations.RemoveField(
            model_name="artical",
            name="banner_title",
        ),
        migrations.RemoveField(
            model_name="articallist",
            name="banner_sub_title",
        ),
        migrations.RemoveField(
            model_name="articallist",
            name="banner_title",
        ),
        migrations.AddField(
            model_name="artical",
            name="sub_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="articallist",
            name="sub_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
