# Generated by Django 4.2.1 on 2023-05-25 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("articles", "0003_remove_artical_banner_sub_title_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticalList",
            new_name="Article",
        ),
        migrations.RenameModel(
            old_name="Artical",
            new_name="ArticleList",
        ),
    ]
