# Generated by Django 4.2.1 on 2023-05-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("articles", "0004_rename_articallist_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Post date"),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="wagtailimages.image"
            ),
        ),
    ]
