# Generated by Django 4.2.1 on 2023-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_article_date_article_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="image",
            new_name="banner_image",
        ),
    ]
