# Generated by Django 4.2.1 on 2023-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_article_summary_alter_article_sub_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlelist",
            name="list_title",
            field=models.CharField(blank=True, default="", help_text="This is shown above the actual list", max_length=255),
        ),
    ]
