# Generated by Django 4.2.1 on 2023-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_articlelist_list_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlelist",
            name="collection_title",
            field=models.CharField(blank=True, default="", help_text="This is shown above any sub lists", max_length=255),
        ),
    ]
