# Generated by Django 4.2.1 on 2023-06-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_articlelist_collection_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlelist",
            name="collection_title",
            field=models.CharField(
                blank=True, default="Article Collections", help_text="This is shown above any sub lists", max_length=255
            ),
        ),
    ]
