# Generated by Django 5.0 on 2024-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_alter_articlelist_collection_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlelist",
            name="collection_title",
            field=models.CharField(blank=True, default="", help_text="This is shown above any sub lists", max_length=255),
        ),
    ]
