[project]
name = "StretchTheirLegs"
version = "2.0.0"
description = "Corporate website for Stretch Their Legs"
authors = [
    {name = "Ben Gosney", email = "bengosney@googlemail.com"},
]
requires-python = ">=3.12.1"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 128
target-version = ['py312']

[tool.pycln]
all = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "stl.settings"
