[project]
name = "Stretch Their Legs"
version = "2.0.0"
description = "Corporate website for Stretch Their Legs"
authors = [
    "Ben Gosney <bengosney@googlemail.com>"
]
python = "^3.10"
homepage = "https://www.stretchtheirlegs.co.uk/"
repository = ""

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 128
target-version = ['py310']

[tool.pycln]
all = true
