version: 2.1
orbs:
  python: circleci/python@3.0.0

jobs:
  test:
    docker:
    - image: cimg/python:3.12.5
    steps:
    - checkout
    - restore_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
    - python/install-packages:
        pip-dependency-file: requirements.dev.txt
        pkg-manager: pip
    - save_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
        paths:
        - /home/circleci/.local/share/virtualenvs
        - /home/circleci/.cache/pip
    - run:
        name: Run tests
        command: python -m pytest

workflows:
  tests:
    jobs:
    - test
