version: 2.1
orbs:
  python: circleci/python@3.0.0

jobs:
  test:
    docker:
    # [[[cog
    # import cog
    # with open(".python-version") as f:
    #   cog.out(f"- image: cimg/python:{f.read().strip()}", dedent=False)
    # ]]]
    - image: cimg/python:3.13
    # [[[end]]] (checksum: 96d6336abf295352f87a27601b1ebe2d)
    steps:
    - checkout
    - restore_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}
    - python/install-packages:
        pip-dependency-file: requirements.dev.txt
        pkg-manager: pip
    - save_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}
        paths:
        - /home/circleci/.local/share/virtualenvs
        - /home/circleci/.cache/pip
    - run:
        name: Run tests
        command: DJANGO_SETTINGS_MODULE=stl.settings.dev python -m pytest

workflows:
  tests:
    jobs:
    - test
