# Generated by Django 4.0.4 on 2022-05-06 07:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_menupage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('Paragraph', wagtail.core.blocks.RichTextBlock())], default=''),
            preserve_default=False,
        ),
    ]
