# Generated by Django 4.0.4 on 2022-05-06 12:50

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_servicepage_body_servicepage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('Paragraph', wagtail.core.blocks.RichTextBlock()), ('Services', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('services', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['pages.ServicePage'])))]))]),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='short_description',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
