# Generated by Django 4.0.4 on 2022-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='google_maps_api_key',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='', help_text='Email address to show in the footer', max_length=150),
        ),
    ]
