# Generated by Django 4.0.4 on 2022-05-23 12:11

from django.db import migrations
import pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_formfield_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('Paragraph', wagtail.blocks.RichTextBlock()), ('Services', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('body', wagtail.blocks.RichTextBlock(required=False)), ('services', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['pages.ServicePage'])))])), ('ImageRow', pages.blocks.FlexBlock(wagtail.images.blocks.ImageChooserBlock))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.fields.StreamField([('Paragraph', wagtail.blocks.RichTextBlock()), ('Services', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('body', wagtail.blocks.RichTextBlock(required=False)), ('services', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['pages.ServicePage'])))])), ('Item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('sub_title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('body', wagtail.blocks.RichTextBlock())])), ('ImageRow', pages.blocks.FlexBlock(wagtail.images.blocks.ImageChooserBlock))], use_json_field=True),
        ),
    ]
