# Generated by Django 4.1.5 on 2023-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_alter_homepage_body_alter_infopage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_sub_title",
            field=models.CharField(default="Dog walking and animal services", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(default="Stretch Their Legs", max_length=60),
            preserve_default=False,
        ),
    ]
