# Generated by Django 4.1.5 on 2023-01-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_homepage_banner_sub_title_homepage_banner_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="sub_title",
            field=models.CharField(blank=True, default="Details", max_length=120),
        ),
    ]
