# Generated by Django 4.2.1 on 2023-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_servicepage_sub_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="sub_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
