# Generated by Django 4.2.1 on 2023-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_formpage_sub_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formpage",
            old_name="sub_title",
            new_name="sub_heading",
        ),
        migrations.AddField(
            model_name="infopage",
            name="sub_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="sub_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
