# Generated by Django 4.0.4 on 2022-05-20 18:48

from django.db import migrations, models
import django.db.models.manager
import fh_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1, verbose_name='Status')),
                ('show_from', fh_utils.fields.DayMonthField(verbose_name='Show From')),
                ('show_to', fh_utils.fields.DayMonthField(verbose_name='Show To')),
                ('logo', models.FileField(upload_to='logos')),
            ],
            options={
                'default_manager_name': 'admin_objects',
            },
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
