# Generated by Django 4.0.4 on 2022-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='title',
            field=models.TextField(default='', verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.FileField(upload_to='logos', verbose_name='Logo SVG'),
        ),
    ]
