# Generated by Django 4.1.3 on 2022-12-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logos", "0002_logo_title_alter_logo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="fireworks",
            field=models.BooleanField(default=False, verbose_name="Show fireworks"),
        ),
    ]
