# Generated by Django 4.1.4 on 2022-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logos", "0003_logo_fireworks"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="snow",
            field=models.BooleanField(default=False, verbose_name="Show snow"),
        ),
    ]
