# Generated by Django 5.0 on 2024-01-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logos", "0007_alter_logo_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="easter",
            field=models.BooleanField(db_default=models.Value(False), verbose_name="Easter"),
        ),
    ]
