# Generated by Django 5.0.2 on 2024-02-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logos", "0008_logo_easter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logo",
            options={"default_manager_name": "admin_objects", "ordering": ["-easter", "show_from"]},
        ),
        migrations.AlterField(
            model_name="logo",
            name="easter",
            field=models.BooleanField(db_default=False, verbose_name="Easter"),
        ),
    ]
