# Generated by Django 4.0.4 on 2022-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_social_delete_ogtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='json_ld',
            field=models.TextField(blank=True),
        ),
    ]
