name: Upgrade dependencies

on:
  workflow_dispatch:

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
      
      - name: Install pip-tools
        run: |
          python -m pip install pip-tools
      
      - name: Upgrade dependencies
        run: |
          python -m piptools compile -q --upgrade requirements.in
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Ben Gosney
          author_email: bengosney@googlemail.com
          message: Update dependencies
          add: requirements.txt
          branch: dependencies-upgrade
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Upgrade dependencies
          branch: dependencies-upgrade
          body: |
            This pull request updates the dependencies specified in the requirements file.
            Please review and merge if everything looks good.
